apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: manual-installer-sept6 
  janus-idp.io/tekton: manual-installer-sept6
  backstage.io/kubernetes-id: manual-installer-sept6
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: manual-installer-sept6
resources: 
- application-dev.yaml