apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: manual-installer-sept6
  janus-idp.io/tekton: manual-installer-sept6
  backstage.io/kubernetes-id: manual-installer-sept6
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: manual-installer-sept6
resources: 
- initialize-namespace.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
