---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: manual-installer-sept6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: manual-installer-sept6 
  name: manual-installer-sept6
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi