apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: manual-installer-sept6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: manual-installer-sept6 
  name: manual-installer-sept6
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: manual-installer-sept6 
